name: Release to VS Code Marketplace
on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install the dependencies
        run: yarn install --frozen-lockfile

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish extension to VSCode marketplace
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: |
          # if the release is a prerelease, we publish a prerelese for the extension too
          if [ "${{ github.event.release.prerelease }}" == "true" ]; then
            vsce publish -p ${{ secrets.VSCE_PAT }} --skip-license --allow-missing-repository --allow-star-activation --pre-release
          else
            vsce publish -p ${{ secrets.VSCE_PAT }} --skip-license --allow-missing-repository --allow-star-activation
          fi
