version = 1

exclude_patterns = [
  "src/rpc/rpc.ts",
  "src/rpc/rpc.client.ts",
  "src/rpc/analyzer.ts",
]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["nodejs"]

[[transformers]]
name = "prettier"
enabled = true
